### ISSUE TITLE
Crash when using with Next.js 13.4.1, 13.4.2 and 13.4.3

### ISSUE THREAD

**Issue by ornakash** [pmndrs/swc-jotai#13] opened 2023-05-10 12:37 UTC
Added the lines to next.config.js as mentioned in the documentation. In older versions everything worked perfectly, but for some reason it doesn't work anymore.

```
experimental: {
    swcPlugins: [
      ["@swc-jotai/debug-label", {}],
      ["@swc-jotai/react-refresh", {}],
    ],
  },
```

When I try to run my application, I am getting the following error:

> PS C:\or\test-app> yarn run dev
> yarn run v1.22.19
> $ next dev
> - ready started server on 0.0.0.0:3000, url: http://localhost:3000
> - info Loaded env from C:\or\test-app\.env.local
> - warn You have enabled experimental feature (swcPlugins) in next.config.js.
> - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
> 

> thread '<unnamed>' panicked at 'assertion failed: prev.start > max', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wasmer-compiler-3.2.1\src\engine\trap\frame_info.rs:224:9
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> - error ./node_modules/next/dist/shared/lib/router/router.js
> Error: failed to process
> 
> Import trace for requested module:
> ./node_modules/next/dist/shared/lib/router/router.js
> - wait compiling...
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wasmer-compiler-3.2.1\src\engine\trap\frame_info.rs:220:39
> - error ./node_modules/next/dist/shared/lib/router/router.js
> Error: failed to process called `Result::unwrap()` on an `Err` value: PoisonError { .. }
> 
> Import trace for requested module:
> ./node_modules/next/dist/shared/lib/router/router.js

Thanks in advance

**Comment by fabio-nettis** [comment] 2023-05-10 14:06
Still happens to me using Next.js v13.4.1, tried pretty much everything. I'm seeing following error in the console output:

```bash
.thread '<unnamed>' panicked at 'assertion failed: prev.start > max', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.1/src/engine/trap/frame_info.rs:224:9

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.1/src/engine/trap/frame_info.rs:220:39
```

Would really appreciate if you could take a look at this. Thank you for the effort.

Comment related to #6

**Comment by KorySchneider** [comment] 2023-05-16 16:40
I am also seeing this error, but only when putting the swc configuration in my `next.config.js`. When moving the configuration to `.swcrc` I do not get the error, but the debug-label package is not working.

**Comment by KorySchneider** [comment] 2023-05-22 10:52
@fabio-nettis The readme for swc-jotai should be updated then, as it currently says to add the plugin configuration to your `.swcrc` file. Or does the configuration need to be added to both `.swcrc` and `next.config.js`?

https://github.com/pmndrs/swc-jotai#usage

cc @Thisen @kdy1

**Comment by KorySchneider** [comment] 2023-05-22 10:54
Either way I am still unable to get these plugins working. Here are the logs:
```
thread '<unnamed>' panicked at 'assertion failed: prev.start > max', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.1/src/engine/trap/frame_info.rs:224:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.1/src/engine/trap/frame_info.rs:220:39
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.1/src/engine/trap/frame_info.rs:220:39
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.1/src/engine/trap/frame_info.rs:220:39
- error ./node_modules/.pnpm/next@13.4.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/shared/lib/fnv1a.js
Error: failed to process

Import trace for requested module:
./node_modules/.pnpm/next@13.4.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/shared/lib/fnv1a.js
./node_modules/.pnpm/next@13.4.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/shared/lib/bloom-filter/hashing.js
./node_modules/.pnpm/next@13.4.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/shared/lib/bloom-filter/base-filter.js
./node_modules/.pnpm/next@13.4.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/shared/lib/bloom-filter/index.js
./node_modules/.pnpm/next@13.4.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/shared/lib/router/router.js
- wait compiling...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.1/src/engine/trap/frame_info.rs:220:39
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.1/src/engine/trap/frame_info.rs:220:39
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.1/src/engine/trap/frame_info.rs:220:39
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-3.2.1/src/engine/trap/frame_info.rs:220:39
- error ./node_modules/.pnpm/next@13.4.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/shared/lib/router/router.js
Error: failed to process called `Result::unwrap()` on an `Err` value: PoisonError { .. }

Import trace for requested module:
./node_modules/.pnpm/next@13.4.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/shared/lib/router/router.js
```

**Comment by fabio-nettis** [comment] 2023-05-22 10:58
@KorySchneider The idea is that when using Next.js it should be added into `next.config.js` otherwise the `.swcrc` file should be used, at least thats the way I've understood it. Maybe the documentation would also benefit from a slight change of wording.

**Comment by ornakash** [comment] 2023-05-22 11:00
@fabio-nettis  I tried to add experimental: {
    swcPlugins: [
      ["@swc-jotai/debug-label", {}],
      ["@swc-jotai/react-refresh", {}],
    ],
  },

to next.config.js and I still get this error. Can you please elaborate on your solution with the .swcrc file?

**Comment by fabio-nettis** [comment] 2023-05-22 11:04
@ornakash This configuration is completely valid according to the docs. But there seems to be a bug in the plugins rendering them unusable with the current next version. Henceforth the creation of this issue.

**Comment by Thisen** [comment] 2023-05-23 07:19
This is a duplicate of #11.

Same issue as here: https://github.com/wasmerio/wasmer/issues/3793

**Closed by Thisen** 2023-05-23 07:19 UTC
